#===================================
# General Params for TabNet
#===================================
MAX_EPOCH: 5
NB_SPLITS: 4

#===================================
# TabNet Model Params
#===================================
n_d: 32
n_a: 32
n_steps: 1
gamma: 1.3
lambda_sparse: 0
